name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.pedanticorderliness.com
          username: ${{ secrets.DOCKER_REG_USER }}
          password: ${{ secrets.DOCKER_REG_PASS }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          tags: |
            docker.pedanticorderliness.com/eco-market:${{ github.sha }}
          context: ./
          file: ./Dockerfile
          push: true
          build-args: |
            GIT_REV=${{ github.sha }}
