name: Build, Push, and Deploy Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.pedanticorderliness.com
          username: ${{ secrets.DOCKER_REG_USER }}
          password: ${{ secrets.DOCKER_REG_PASS }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          tags: |
            docker.pedanticorderliness.com/eco-market:${{ github.sha }}
          context: ./
          file: ./Dockerfile
          push: true
          build-args: |
            GIT_REV=${{ github.sha }}

  deploy:
    name: Deploy
    needs: [build_and_push]
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.PO_APP_ID }}
          private_key: ${{ secrets.PO_PRIVATE_KEY }}

      - name: Update image tag
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh workflow run image_update.yaml \
            -R ryanrolds/infrastructure \
            -r main \
            -F chart=eco-market \
            -F values_file=./values.yaml \
            -F tag_path=image.tag \
            -F tag=${{ github.sha }} \
            -F branch=main
